### ISSUE TITLE
get_context_instance() deprecated since, use context_xxxx::instance() instead.

### ISSUE THREAD

**Issue by sensei-hacker** [marxjohnson/moodle-block_quickfindlist#10]
master (Moodle 2.6DEV) throws this warning:

get_context_instance() is deprecated, please use context_xxxx::instance() instead.

In deprecatedlib.php, I see get_context_instance has been deprecated since 2.2.

On line #97 of blocks/quickfindlist/block_quickfindlist.php, change:

$context_system = get_context_instance(CONTEXT_SYSTEM);

to:

 $context_system = context_system::instance();

**Comment by devXela** [comment]
tks!
