### ISSUE TITLE
moodle 3.2

### ISSUE THREAD

**Issue by Meirk8** [marxjohnson/moodle-block_quickfindlist#19]
could you develop the block for moodle ver 3.2

**Comment by vicden** [comment]
And 3.3/3.4?
Awesome block, I'm not ready to leave it behind

**Comment by nstefanski** [comment]
So, it seems like the block as it appears here on the GitHub repo works with Moodle 3.4, at least I haven't noticed any issues. However, the plugin that is listed on the official Moodle plugins list seems to encounter some issues beyond 3.1 (can no longer configure instances, cannot search with spaces in the name). Could you gentlemen update the Moodle plugins list with the latest version here? I think that would solve a lot of folks' problems.

**Comment by MorrisR2** [comment]
nstefanski can you please try the version I just deployed to the plugin database. I no longer have a Moodle installation to test with, but I downloaded from GitHub and put it in the plugin directory.  Thanks.

**Comment by nstefanski** [comment]
Works perfectly on my dev site! Thanks for the quick response!

**Comment by marxjohnson** [comment]
Thanks for sorting that out @MorrisR2!
