### ISSUE TITLE
pix_url is deprecated

### ISSUE THREAD

**Issue by agrowe** [marxjohnson/moodle-block_quickfindlist#23]
On Line 126 of block_quickfindlist.php change `pix_url` to `image_url`

**Comment by davidpesce** [comment]
Confirming this as an error. And the fix works.

**Comment by davidpesce** [comment]
This is fixed per commit https://github.com/marxjohnson/moodle-block_quickfindlist/commit/2c4a5b87aae9ba385dcf589ac8d3261f7a0f6441
